version: '3'

services:
  influxdb:
    restart: always
    image: influxdb:1.7
    ports:
      - "${PORT}/udp:8086/udp"
      - "${PORT}/tcp:8086/tcp"
    volumes:
      - ${DATA_DIRECTORY}:/var/lib/influxdb